version: '3'

services:
  redis-serverless:
    image: redis
    command: redis-server
    hostname: redis
    ports:
      - "6379:6379"
  mongo-serverless:
    image: mongo
    restart: always
    ports: 
      - 27017:27017

  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8081:8080"
    volumes:
      - ./swagger.json:/swagger.json
    environment:
      SWAGGER_FILE: /swagger.json

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    volumes:
      - ./swagger.json:/swagger.json
    environment:
      SWAGGER_JSON: /swagger.json

  swagger-api:
    image: danielgtaylor/apisprout
    ports:
      - "8083:8000"
    volumes:
      - ./swagger.json:/swagger.json
    command: /swagger.json
    networks:
      swagger_link:
        aliases:
          - local.swagger.apisprout

  swagger-nginx:
    image: nginx:mainline-alpine
    ports:
      - "8084:8084"
    networks:
      swagger_link:
        aliases:
          - local.swagger.api

networks:
  swagger_link:
    external: false
