service: serverless-node-interview
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  get:
    handler: controllers/get.handler # cnpj.get
    events:
      - httpApi:
          path: /process/customers
          method: get
  post:
    handler: controllers/post.handler
    events:
      - httpApi:
          path: /process/customers
          method: post

  process:
    handler: controllers/process.handler
    events:
      - schedule: rate(1 minute)

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-offline-redis-server
  - serverless-mongodb-local
